### ISSUE TITLE
NullReferenceException occurs when executing specific sc calls

### ISSUE THREAD

**Issue by adrianocorneia** [stratisproject/StratisphereWallet#7]
Different error message than the other issue. This is when trying to execute a marketplace request (smart contract call):

<img width="588" alt="image" src="https://user-images.githubusercontent.com/85025908/162895856-18ebbb63-5edc-4055-9bad-a6f4f7f01c2f.png">

**Comment by adrianocorneia** [comment]
I think it is related to the `parameters` of that specific request being empty.

**Comment by noescape00** [comment]
fixed
